### ISSUE TITLE
Dataset pattern

### ISSUE THREAD

**Issue by Yisher** [SamsungLabs/Noise2NoiseFlow#5]
Hello,reasercher, thanks for your excellent work.I'm confused by the dataset distribution,because [Noise2NoiseFlow(https://github.com/SamsungLabs/Noise2NoiseFlow/tree/main/sRGB_noise_modeling/eecs.yorku.ca/~kamel/sidd/dataset.php/) meet a 404 error.And I find the origin sidd dataset,but I don't know whether you adopted the distribution of original dataset
I want to know whether the dataset looks like this:

sidd
├── input
│ ├── xxx1.PNG
│ └── xxx2.PNG
│ └── ...
└── GT
├── xxx1.PNG
└── xxx2.PNG
└── ...

hope for your attention，my goal is train my own data to get the noise model ,and use it to generate new noise in synthesize image, May I ask you for your kind help about what should I do to prepare my data and utilize your code(sRGB noise model)？

**Comment by Yisher** [comment]
my goal is train my own data to get the noise model ,and use it to generate new noise in synthesize image, May I ask you for your kind help about what should I do to prepare my data and utilize your code?

**Comment by AliMaleky7997** [comment]
We use the same SIDD-Medium format available on the SIDD website. The directory hierarchy remains the same.
You can write your own data loader to load your custom data the same way we do, hopefully, everything else should work automatically.
